# prometheus/prometheus.yml

global:
  scrape_interval: 15s # How often to scrape metrics

scrape_configs:
  # Job to scrape metrics from the FastAPI application
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']

  # Job to scrape metrics from the Celery worker
  # Note: Your worker code must be updated to run an http server on this port
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:8001']